name: Sync Dev with Signet
on:
  push:
    branches:
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Push to target branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BRANCH_SYNC_ORDINARIUS_TOKEN }}
          branch: signet
          force: true
